<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXSkJ36D\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXSkJ36D/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXSkJ36D.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXSkJ36D\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXSkJ36D\App_KernelDevDebugContainer([
    'container.build_hash' => 'XSkJ36D',
    'container.build_id' => '4799be3d',
    'container.build_time' => 1761933186,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXSkJ36D');
